export { CompanyWatchService } from './company-watch-service.js';
export type { SyncResult } from './company-watch-service.js';
export { NormalizationService } from './normalization-service.js';
export type { NormalizedJob } from './normalization-service.js';
export { DeduplicationService } from './deduplication-service.js';
export type { JobChange } from './deduplication-service.js';
export { CompanyDiscoveryService } from './company-discovery-service.js';
export type { DiscoveryResult } from './company-discovery-service.js';
export { CandidateDeduplicationService } from './candidate-deduplication-service.js';
export type { NearestNameMatch } from './candidate-deduplication-service.js';
export { CompanyDiscoveryIntakeService } from './company-discovery-intake-service.js';
export type { DiscoverCandidateInput, DiscoverCandidateOutcome } from './company-discovery-intake-service.js';
export { VacancyDiscoveryBridge } from './vacancy-discovery-bridge.js';
export type { VacancyDiscoveryBridgeConfig, VacancyDiscoveryResult, VacancyForDiscovery, Logger as VacancyDiscoveryLogger } from './vacancy-discovery-bridge.js';
