export const VacancySource = {
  LINKEDIN: 'linkedin',
  HH: 'hh',
  HABR_CAREER: 'habr_career',
  REMOTE_OK: 'remote_ok',
  WELLFOUND: 'wellfound',
  OTTA: 'otta',
  RSS_FEED: 'rss_feed',
  COMPANY_CAREER_PAGE: 'company_career_page',
  TELEGRAM: 'telegram',
  MANUAL: 'manual',
  GREENHOUSE: 'greenhouse',
  LEVER: 'lever',
  ASHBY: 'ashby',
  WORKDAY: 'workday',
  TEAMTAILOR: 'teamtailor',
  REMOTIVE: 'remotive',
  HIMALAYAS: 'himalayas',
  ARBEITNOW: 'arbeitnow',
  JOBICY: 'jobicy',
  WE_WORK_REMOTELY: 'we_work_remotely',
  WORKING_NOMADS: 'working_nomads',
  NODESK: 'nodesk',
  HN_HIRING: 'hn_hiring',
  SMARTRECRUITERS: 'smartrecruiters',
  RECRUITEE: 'recruitee',
  SUPERJOB: 'superjob',
  COMEET: 'comeet',
} as const;

export type VacancySource = (typeof VacancySource)[keyof typeof VacancySource];
